Update to latest version of viash.

diff --git a/bin/init b/bin/init
--- a/bin/init
+++ b/bin/init
@@ -1,4 +1,44 @@
 #!/bin/bash
+PROGNAME=${0##*/}
+usage() {
+  echo "Usage: ${PROGNAME} [-n] [-h]"
+}
+
+help_message() {
+  cat <<- EOF
+	${PROGNAME}
+	
+	Download nextflow and viash binaries into the 'bin' folder
+
+	$(usage)
+
+	Options:
+	-n		Download viash only.
+	-h		Display this help message and exit.
+
+	EOF
+}
+
+only_viash=false
+while getopts ":hn" opt; do
+  case ${opt} in
+    h ) help_message
+        exit 0;
+        ;;
+    n ) only_viash=true
+        ;;
+    \? ) >&2 echo "Invalid Option: -${OPTARG}" 1>&2
+         help_message
+         exit 1;
+         ;;
+    : )
+         >&2 echo "Invalid Option: -${OPTARG} requires an argument" 1>&2
+         help_message
+         exit 1
+         ;;
+  esac
+done
+
 
 # get the root of the directory
 REPO_ROOT=$(git rev-parse --show-toplevel)
@@ -6,14 +46,12 @@ REPO_ROOT=$(git rev-parse --show-toplevel)
 # ensure that the command below is run from the root of the repository
 cd "$REPO_ROOT"
 
-# download viash and viash project executables
-curl -fsSL get.viash.io | bash -s -- \
-  --registry ghcr.io \
-  --organisation viash-io/viash_project_template \
-  --target_image_source https://github.com/viash-io/viash_project_template \
-  --tag 0.5.15 \
-  --nextflow_variant vdsl3
+curl -fsSL get.viash.io | bash -s -- --tools false
 
-# download nextflow
-cd bin
-curl -s https://get.nextflow.io | bash
+if [ "$only_viash" = false ] ; then
+
+  cd bin
+
+  curl -s https://get.nextflow.io | bash
+
+fi
